import { jsPDF } from 'jspdf';
import { format } from 'date-fns';
import type { Invoice, Client } from './types';
import { toTitleCase } from './utils';

// HSL to RGB conversion
function hslToRgb(h: number, s: number, l: number): [number, number, number] {
    let r, g, b;
    if (s === 0) {
        r = g = b = l; // achromatic
    } else {
        const hue2rgb = (p: number, q: number, t: number) => {
            if (t < 0) t += 1;
            if (t > 1) t -= 1;
            if (t < 1 / 6) return p + (q - p) * 6 * t;
            if (t < 1 / 2) return q;
            if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
            return p;
        };
        const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
        const p = 2 * l - q;
        r = hue2rgb(p, q, h + 1 / 3);
        g = hue2rgb(p, q, h);
        b = hue2rgb(p, q, h - 1 / 3);
    }
    return [Math.round(r * 255), Math.round(g * 255), Math.round(b * 255)];
}

// Brand colors from globals.css
const primaryHsl = { h: 180 / 360, s: 1, l: 0.25 }; // HSL(180, 100%, 25%)
const primaryRgb = hslToRgb(primaryHsl.h, primaryHsl.s, primaryHsl.l);
const black = [0, 0, 0];
const gray = [102, 112, 132];
const lightGray = [241, 245, 249]; // A light gray for table backgrounds
const white = [255, 255, 255];
const borderGray = [226, 232, 240];

const brandName = 'GigBillow';
const pageMargin = 40;

function addHeader(doc: jsPDF, title: string) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(28);
    doc.setTextColor(...primaryRgb);
    doc.text(title, pageMargin, pageMargin, { align: 'left' });
}

function addWatermark(doc: jsPDF) {
    const pageCount = (doc as any).internal.getNumberOfPages();
    doc.setFontSize(8);
    doc.setTextColor(...gray);

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        const footerText = `Generated by ${brandName}`;
        doc.text(footerText, doc.internal.pageSize.getWidth() - pageMargin, doc.internal.pageSize.getHeight() - 20, { align: 'right' });
    }
}

function generatePdf(fileName: string, title: string, removeWatermark: boolean, addContent: (doc: jsPDF) => void) {
    const doc = new jsPDF('p', 'pt', 'a4');
    doc.setFont('helvetica');

    addHeader(doc, title);
    addContent(doc);
    if (!removeWatermark) {
        addWatermark(doc);
    }
    doc.save(`${fileName}.pdf`);
}


// --- INVOICE PDF ---
type GenerateInvoicePdfProps = {
    invoice: Invoice;
    client: Client;
    user: { displayName?: string | null; email?: string | null };
    removeWatermark?: boolean;
};

export function generateInvoicePdf({ invoice, client, user, removeWatermark = false }: GenerateInvoicePdfProps) {
    const addContent = (doc: jsPDF) => {
        let y = pageMargin + 60;
        const sectionGap = 20;
        const itemGap = 15;
        const rightColX = doc.internal.pageSize.getWidth() / 2 + 60;

        // --- From / To Info ---
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...primaryRgb);
        doc.text('FROM', pageMargin, y);
        doc.text('ISSUED TO', pageMargin, y + 70);

        doc.setFontSize(11);
        doc.setTextColor(...black);
        doc.setFont('helvetica', 'bold');
        doc.text(user.displayName || 'Freelancer', pageMargin, y + itemGap);
        doc.text(client.name, pageMargin, y + 70 + itemGap);
        
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...gray);
        doc.text(user.email || '', pageMargin, y + itemGap * 2);
        doc.text(client.email, pageMargin, y + 70 + itemGap * 2);

        // --- Invoice Details (Right Column) ---
        const details = [
            { label: 'Invoice Number:', value: invoice.invoiceNumber },
            { label: 'Issue Date:', value: format(new Date(invoice.issuedDate), 'PPP') },
            { label: 'Due Date:', value: format(new Date(invoice.dueDate), 'PPP') },
        ];
        
        details.forEach((detail, i) => {
            const detailY = y + (i * (itemGap + 2));
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(...primaryRgb);
            doc.text(detail.label, rightColX, detailY, { align: 'left' });
            
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...black);
            doc.text(detail.value, rightColX + 90, detailY, { align: 'left' });
        });

        y += 140;

        // --- Separator before summary ---
        doc.setDrawColor(...borderGray);
        doc.line(pageMargin, y - sectionGap, doc.internal.pageSize.getWidth() - pageMargin, y - sectionGap);
        
        // --- AI Enhanced Summary ---
        if (invoice.enhancedSummary) {
            doc.setFontSize(11);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...black);
            doc.setLineHeightFactor(1.5);
            const summaryLines = doc.splitTextToSize(invoice.enhancedSummary, doc.internal.pageSize.getWidth() - (pageMargin * 2));
            doc.text(summaryLines, pageMargin, y);
            y += (summaryLines.length * itemGap * 1.5) + sectionGap;
        }

        // --- Line Items Table ---
        const tableTop = y;
        const numberColX = pageMargin;
        const descriptionColX = numberColX + 40;
        const tableWidth = doc.internal.pageSize.getWidth() - pageMargin * 2;
        
        // Draw table header
        doc.setFillColor(...primaryRgb);
        doc.rect(pageMargin, tableTop, tableWidth, 25, 'F');

        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...white);
        doc.text('#', numberColX + 10, tableTop + 16);
        doc.text('DESCRIPTION', descriptionColX, tableTop + 16);
        
        y = tableTop + 25; // Move Y to below the header
        
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...black);

        invoice.lineItems.forEach((item, index) => {
            const isEvenRow = index % 2 === 0;
            const splitDescription = doc.splitTextToSize(toTitleCase(item.description), tableWidth - (descriptionColX - pageMargin));
            const rowHeight = (splitDescription.length * (itemGap - 2)) + 10;

            // Draw row background
            if (!isEvenRow) {
                doc.setFillColor(...lightGray);
                doc.rect(pageMargin, y, tableWidth, rowHeight, 'F');
            }

            const itemY = y + 15;
            const itemNumber = `${index + 1}.`;
            
            doc.text(itemNumber, numberColX + 10, itemY);
            doc.text(splitDescription, descriptionColX, itemY);
            y += rowHeight;
        });

        // Draw table borders
        doc.setDrawColor(...borderGray);
        doc.rect(pageMargin, tableTop, tableWidth, y - tableTop); // Outer border
        doc.line(descriptionColX - 10, tableTop, descriptionColX - 10, y); // Vertical line after #
        
        y += itemGap;

        // --- Totals ---
        const totalsX = doc.internal.pageSize.getWidth() - pageMargin - 200;
        doc.line(totalsX - 20, y, doc.internal.pageSize.getWidth() - pageMargin, y);
        y += itemGap + 2;
        
        const subTotal = Number(invoice.subTotal) || 0;
        const expensesTotal = Number(invoice.expensesTotal) || 0;
        const servicesTotal = subTotal - expensesTotal;
        const discount = Number(invoice.discount) || 0;
        const discountedSubTotal = subTotal - discount;
        const taxRate = Number(invoice.taxRate) || 0;
        const taxAmount = (discountedSubTotal * taxRate) / 100;
        const totalAmount = Number(invoice.amount) || 0;

        const totals = [
            ...(servicesTotal > 0 && expensesTotal > 0 ? [{ label: 'Services', value: `$${servicesTotal.toFixed(2)}` }] : []),
            ...(expensesTotal > 0 ? [{ label: 'Expenses', value: `$${expensesTotal.toFixed(2)}` }] : []),
            { label: 'Sub-total', value: `$${subTotal.toFixed(2)}` },
            ...(discount > 0 ? [{ label: 'Discount', value: `-$${discount.toFixed(2)}`, color: gray }] : []),
            { label: `Tax (${taxRate}%)`, value: `$${taxAmount.toFixed(2)}` },
            { label: 'Total', value: `$${totalAmount.toFixed(2)}`, bold: true },
        ];

        doc.setFontSize(10);
        totals.forEach(t => {
            doc.setFont('helvetica', t.bold ? 'bold' : 'normal');
            doc.setTextColor(...(t.color || (t.bold ? black : gray)));
            doc.text(t.label, totalsX, y, { align: 'left' });
            doc.text(t.value, doc.internal.pageSize.getWidth() - pageMargin, y, { align: 'right' });
            y += itemGap + (t.bold ? 4 : 2);
        });
        y += sectionGap;

        // --- Notes & Payment ---
        if (invoice.notes || invoice.paymentUrl) {
            y += sectionGap / 2;
            if (invoice.notes) {
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(...black);
                doc.text('Notes', pageMargin, y);
                y += itemGap;
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(...gray);
                const noteLines = doc.splitTextToSize(toTitleCase(invoice.notes), doc.internal.pageSize.getWidth() - (pageMargin * 2));
                doc.text(noteLines, pageMargin, y);
                y += (noteLines.length * itemGap) + sectionGap;
            }
            if (invoice.paymentUrl) {
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(...black);
                doc.text('Payment Link:', pageMargin, y);
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(59, 130, 246); // A nice blue for links
                doc.textWithLink(invoice.paymentUrl, pageMargin + 75, y, { url: invoice.paymentUrl });
                y += itemGap;
            }
        }
    };
    
    generatePdf(invoice.invoiceNumber, 'INVOICE', removeWatermark, addContent);
}

// --- PROPOSAL PDF ---
type GenerateProposalPdfProps = {
    proposalText: string;
    clientName?: string;
    removeWatermark?: boolean;
};

export function generateProposalPdf({ proposalText, clientName, removeWatermark = false }: GenerateProposalPdfProps) {
    const addContent = (doc: jsPDF) => {
        let y = pageMargin + 80;

        doc.setFontSize(10);
        doc.setTextColor(...gray);
        doc.text(`DATE: ${format(new Date(), 'PPP')}`, pageMargin, y);
        if (clientName) {
            doc.text(`TO: ${clientName}`, doc.internal.pageSize.getWidth() - pageMargin, y, { align: 'right' });
        }
        y += 30;
        doc.setDrawColor(...borderGray); // border color
        doc.line(pageMargin, y, doc.internal.pageSize.getWidth() - pageMargin, y);
        y += 40;
        
        doc.setFontSize(11);
        doc.setTextColor(...black);
        doc.setLineHeightFactor(1.5);
        const textLines = doc.splitTextToSize(proposalText, doc.internal.pageSize.getWidth() - pageMargin * 2);
        
        textLines.forEach((line: string) => {
            if (y > doc.internal.pageSize.getHeight() - pageMargin - 40) {
                doc.addPage();
                addHeader(doc, 'Project Proposal');
                y = pageMargin + 40;
            }
            doc.text(line, pageMargin, y);
            if (line.trim() === '') {
                 y += 7; // smaller gap for paragraph breaks
            } else {
                 y += 15; // standard line height
            }
        });
    };

    generatePdf('Project-Proposal', 'Project Proposal', removeWatermark, addContent);
}
