
import { jsPDF } from 'jspdf';
import { format } from 'date-fns';
import type { Invoice, Client } from './types';

// HSL to RGB conversion
function hslToRgb(h: number, s: number, l: number): [number, number, number] {
    let r, g, b;
    if (s === 0) {
        r = g = b = l; // achromatic
    } else {
        const hue2rgb = (p: number, q: number, t: number) => {
            if (t < 0) t += 1;
            if (t > 1) t -= 1;
            if (t < 1 / 6) return p + (q - p) * 6 * t;
            if (t < 1 / 2) return q;
            if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
            return p;
        };
        const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
        const p = 2 * l - q;
        r = hue2rgb(p, q, h + 1 / 3);
        g = hue2rgb(p, q, h);
        b = hue2rgb(p, q, h - 1 / 3);
    }
    return [Math.round(r * 255), Math.round(g * 255), Math.round(b * 255)];
}

// Brand colors from globals.css
const primaryHsl = { h: 180 / 360, s: 1, l: 0.25 }; // HSL(180, 100%, 25%)
const primaryRgb = hslToRgb(primaryHsl.h, primaryHsl.s, primaryHsl.l);

const MutedForegroundRgb = [100, 116, 139]; // approx text-muted-foreground

const brandName = 'ProManFlow';

class PDFDocument extends jsPDF {
    private readonly pageMargin = 20;

    constructor() {
        super('p', 'pt', 'a4');
        this.setFont('helvetica');
    }

    private addHeader(title: string) {
        this.setFontSize(24);
        this.setFont('helvetica', 'bold');
        this.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
        this.text(title, this.pageMargin, this.pageMargin + 20);
    }

    private addFooter() {
        const pageCount = (this as any).internal.getNumberOfPages();
        this.setFontSize(8);
        this.setTextColor(MutedForegroundRgb[0], MutedForegroundRgb[1], MutedForegroundRgb[2]);

        for (let i = 1; i <= pageCount; i++) {
            this.setPage(i);
            const footerText = `Generated by ${brandName}`;
            const textWidth = this.getStringUnitWidth(footerText) * this.getFontSize() / this.internal.scaleFactor;
            this.text(footerText, this.internal.pageSize.getWidth() - this.pageMargin - textWidth, this.internal.pageSize.getHeight() - this.pageMargin);
        }
    }
    
    public generate(fileName: string, title: string, addContent: (doc: PDFDocument) => void) {
        this.addHeader(title);
        addContent(this);
        this.addFooter(); // Call again to ensure footer is on all pages
        this.save(`${fileName}.pdf`);
    }

    get pageHeight() {
        return this.internal.pageSize.getHeight();
    }
    
    get pageWidth() {
        return this.internal.pageSize.getWidth();
    }

    get margin() {
        return this.pageMargin;
    }
}

// --- INVOICE PDF ---
type GenerateInvoicePdfProps = {
    invoice: Invoice;
    client: Client;
    user: { displayName?: string | null; email?: string | null };
};

export function generateInvoicePdf({ invoice, client, user }: GenerateInvoicePdfProps) {
    const doc = new PDFDocument();
    
    const addContent = (doc: PDFDocument) => {
        let y = doc.margin + 60;
        const sectionGap = 25;
        const itemGap = 10;
        const rightColX = doc.pageWidth / 2 + 15;

        // From/To Info
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text('From:', doc.margin, y);
        doc.text('Bill To:', rightColX, y);

        y += itemGap + 5;
        doc.setFont('helvetica', 'normal');
        doc.text(user.displayName || 'Freelancer', doc.margin, y);
        doc.text(client.name, rightColX, y);
        y += itemGap;
        doc.text(user.email || '', doc.margin, y);
        doc.text(client.email, rightColX, y);
        y += sectionGap;

        // Invoice Details
        doc.setDrawColor(200, 200, 200);
        doc.line(doc.margin, y, doc.pageWidth - doc.margin, y);
        y += itemGap;
        
        const details = [
            { label: 'Invoice Number:', value: invoice.invoiceNumber },
            { label: 'Issue Date:', value: format(new Date(invoice.issuedDate), 'PPP') },
            { label: 'Due Date:', value: format(new Date(invoice.dueDate), 'PPP') },
        ];
        
        y += 5;
        details.forEach(detail => {
            doc.setFont('helvetica', 'bold');
            doc.text(detail.label, doc.margin, y);
            doc.setFont('helvetica', 'normal');
            doc.text(detail.value, doc.margin + 100, y);
            y += itemGap;
        });
        y += 5;
        doc.line(doc.margin, y, doc.pageWidth - doc.margin, y);
        y += sectionGap;

        // Enhanced Summary
        if (invoice.enhancedSummary) {
            doc.setFontSize(11);
            doc.setFont('helvetica', 'bold');
            doc.text('Summary', doc.margin, y);
            y += itemGap + 5;
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            const summaryLines = doc.splitTextToSize(invoice.enhancedSummary, doc.pageWidth - (doc.margin * 2));
            doc.text(summaryLines, doc.margin, y);
            y += (summaryLines.length * 10) + sectionGap;
        }

        // Line Items Table
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text('Description', doc.margin, y);
        y += itemGap + 5;
        doc.setDrawColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
        doc.line(doc.margin, y, doc.pageWidth - doc.margin, y);
        y += itemGap;
        
        doc.setFont('helvetica', 'normal');
        invoice.lineItems.forEach(item => {
            const splitDescription = doc.splitTextToSize(item.description, doc.pageWidth - (doc.margin * 2));
            doc.text(splitDescription, doc.margin, y);
            y += (splitDescription.length * 10) + 5;
        });
        y += itemGap;

        // Totals
        const totalsX = doc.pageWidth - doc.margin - 160;
        doc.line(totalsX - 10, y, doc.pageWidth - doc.margin, y);
        y += itemGap + 2;

        const taxAmount = (invoice.subTotal * invoice.taxRate) / 100;
        const totals = [
            { label: 'Sub-total:', value: `$${invoice.subTotal.toFixed(2)}` },
            { label: `Tax (${invoice.taxRate}%):`, value: `$${taxAmount.toFixed(2)}` },
            { label: 'Total:', value: `$${invoice.amount.toFixed(2)}`, bold: true },
        ];

        totals.forEach(t => {
            doc.setFont('helvetica', t.bold ? 'bold' : 'normal');
            doc.text(t.label, totalsX, y, { align: 'left' });
            doc.text(t.value, doc.pageWidth - doc.margin, y, { align: 'right' });
            y += itemGap + 2;
        });
        y += sectionGap;

        // Notes & Payment
        if (invoice.notes || invoice.paymentUrl) {
            if (invoice.notes) {
                doc.setFont('helvetica', 'bold');
                doc.text('Notes', doc.margin, y);
                y += itemGap;
                doc.setFont('helvetica', 'normal');
                const noteLines = doc.splitTextToSize(invoice.notes, doc.pageWidth - (doc.margin * 2));
                doc.text(noteLines, doc.margin, y);
                y += (noteLines.length * 10) + itemGap;
            }
            if (invoice.paymentUrl) {
                doc.setFont('helvetica', 'bold');
                doc.text('Payment Link:', doc.margin, y);
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(0, 0, 255);
                doc.textWithLink(invoice.paymentUrl, doc.margin + 80, y, { url: invoice.paymentUrl });
                doc.setTextColor(0, 0, 0);
                y += itemGap;
            }
        }
    };
    
    doc.generate(invoice.invoiceNumber, 'INVOICE', addContent);
}

// --- PROPOSAL PDF ---
type GenerateProposalPdfProps = {
    proposalText: string;
    clientName?: string;
};

export function generateProposalPdf({ proposalText, clientName }: GenerateProposalPdfProps) {
    const doc = new PDFDocument();

    const addContent = (doc: PDFDocument) => {
        let y = doc.margin + 60;

        // Date and Client Info
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.text(`Date: ${format(new Date(), 'PPP')}`, doc.margin, y);
        if (clientName) {
            doc.text(`To: ${clientName}`, doc.pageWidth - doc.margin, y, { align: 'right' });
        }
        y += 20;
        doc.setDrawColor(200, 200, 200);
        doc.line(doc.margin, y, doc.pageWidth - doc.margin, y);
        y += 30;
        
        // Proposal Body
        doc.setFontSize(11);
        doc.setTextColor(50,50,50);
        const textLines = doc.splitTextToSize(proposalText, doc.pageWidth - doc.margin * 2);
        
        textLines.forEach((line: string) => {
            if (y > doc.pageHeight - doc.margin - 20) {
                doc.addPage();
                y = doc.margin + 20;
            }
            doc.text(line, doc.margin, y);
            y += 15; // Line height
        });
    };

    doc.generate('proposal', 'Project Proposal', addContent);
}
