

import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';
import type { Invoice, Client, UserProfile } from './types';
import { toTitleCase } from './utils';

// HSL to RGB conversion
function hslToRgb(h: number, s: number, l: number): [number, number, number] {
    let r, g, b;
    if (s === 0) {
        r = g = b = l; // achromatic
    } else {
        const hue2rgb = (p: number, q: number, t: number) => {
            if (t < 0) t += 1;
            if (t > 1) t -= 1;
            if (t < 1 / 6) return p + (q - p) * 6 * t;
            if (t < 1 / 2) return q;
            if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
            return p;
        };
        const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
        const p = 2 * l - q;
        r = hue2rgb(p, q, h + 1 / 3);
        g = hue2rgb(p, q, h);
        b = hue2rgb(p, q, h - 1 / 3);
    }
    return [Math.round(r * 255), Math.round(g * 255), Math.round(b * 255)];
}

// Brand colors from globals.css
const primaryHsl = { h: 180 / 360, s: 1, l: 0.25 }; // HSL(180, 100%, 25%)
const primaryRgb = hslToRgb(primaryHsl.h, primaryHsl.s, primaryHsl.l);
const black = [0, 0, 0];
const gray = [102, 112, 132];
const lightGray = [241, 245, 249]; // A light gray for table backgrounds
const white = [255, 255, 255];
const borderGray = [226, 232, 240];

const brandName = 'GigBillow';
const pageMargin = 40;

async function addHeader(doc: jsPDF, title: string, logoUrl?: string) {
    // Fallback text header
    const fallbackHeader = () => {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(28);
        doc.setTextColor(...primaryRgb);
        doc.text(title, pageMargin, pageMargin, { align: 'left' });
    };

    if (logoUrl) {
        try {
            // Create an Image object and load the data URI
            const img = new Image();
            img.src = logoUrl;
            
            // Wait for the image to load
            await new Promise<void>((resolve, reject) => {
                img.onload = () => resolve();
                img.onerror = (err) => reject(err);
            });
            
            const logoHeight = 40;
            const logoWidth = (img.width * logoHeight) / img.height;
            // Pass the loaded image object, not the URL, to addImage
            doc.addImage(img, pageMargin, pageMargin - 15, logoWidth, logoHeight);

        } catch (error) {
            console.error("Failed to load logo image from Data URI:", error);
            fallbackHeader();
        }
    } else {
        fallbackHeader();
    }
}

function addWatermark(doc: jsPDF) {
    const pageCount = (doc as any).internal.getNumberOfPages();
    doc.setFontSize(8);
    doc.setTextColor(...gray);

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        const footerText = `Generated by ${brandName}`;
        doc.text(footerText, doc.internal.pageSize.getWidth() - pageMargin, doc.internal.pageSize.getHeight() - 20, { align: 'right' });
    }
}

async function generatePdf(fileName: string, title: string, removeWatermark: boolean, addContent: (doc: jsPDF) => void, logoUrl?: string) {
    const doc = new jsPDF('p', 'pt', 'a4');
    doc.setFont('helvetica');

    await addHeader(doc, title, logoUrl);
    addContent(doc);
    if (!removeWatermark) {
        addWatermark(doc);
    }
    doc.save(`${fileName}.pdf`);
}


// --- INVOICE PDF ---
type GenerateInvoicePdfProps = {
    invoice: Invoice;
    client: Client;
    user: UserProfile;
    removeWatermark?: boolean;
};

export async function generateInvoicePdf({ invoice, client, user, removeWatermark = false }: GenerateInvoicePdfProps) {
    const addContent = (doc: jsPDF) => {
        let y = pageMargin + 60;
        const sectionGap = 20;
        const itemGap = 15;
        const rightColX = doc.internal.pageSize.getWidth() / 2 + 60;

        // --- From / To Info ---
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...primaryRgb);
        doc.text('FROM', pageMargin, y);
        doc.text('ISSUED TO', pageMargin, y + 70);

        doc.setFontSize(11);
        doc.setTextColor(...black);
        doc.setFont('helvetica', 'bold');
        doc.text(user.displayName || 'Freelancer', pageMargin, y + itemGap);
        doc.text(client.name, pageMargin, y + 70 + itemGap);
        
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...gray);
        doc.text(user.email || '', pageMargin, y + itemGap * 2);
        doc.text(client.email, pageMargin, y + 70 + itemGap * 2);

        // --- Invoice Details (Right Column) ---
        const details = [
            { label: 'Invoice Number:', value: invoice.invoiceNumber },
            { label: 'Issue Date:', value: format(new Date(invoice.issuedDate), 'PPP') },
            { label: 'Due Date:', value: format(new Date(invoice.dueDate), 'PPP') },
        ];
        
        details.forEach((detail, i) => {
            const detailY = y + (i * (itemGap + 2));
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(...primaryRgb);
            doc.text(detail.label, rightColX, detailY, { align: 'left' });
            
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...black);
            doc.text(detail.value, rightColX + 90, detailY, { align: 'left' });
        });

        y += 140;

        // --- Separator before summary ---
        doc.setDrawColor(...borderGray);
        doc.line(pageMargin, y - sectionGap, doc.internal.pageSize.getWidth() - pageMargin, y - sectionGap);
        
        // --- AI Enhanced Summary ---
        if (invoice.enhancedSummary) {
            doc.setFontSize(11);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...black);
            doc.setLineHeightFactor(1.5);
            const summaryLines = doc.splitTextToSize(invoice.enhancedSummary, doc.internal.pageSize.getWidth() - (pageMargin * 2));
            doc.text(summaryLines, pageMargin, y);
            y += (summaryLines.length * itemGap * 1.5) + sectionGap;
        }

        // --- Line Items Table ---
        const tableTop = y;
        const numberColX = pageMargin;
        const descriptionColX = numberColX + 40;
        const tableWidth = doc.internal.pageSize.getWidth() - pageMargin * 2;
        
        // Draw table header
        doc.setFillColor(...primaryRgb);
        doc.rect(pageMargin, tableTop, tableWidth, 25, 'F');

        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...white);
        doc.text('#', numberColX + 10, tableTop + 16);
        doc.text('DESCRIPTION', descriptionColX, tableTop + 16);
        
        y = tableTop + 25; // Move Y to below the header
        
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...black);

        const allLineItems = [...invoice.lineItems];
        if (invoice.expensesTotal && invoice.expensesTotal > 0) {
            allLineItems.push({ description: `Reimbursable Expenses` });
        }


        allLineItems.forEach((item, index) => {
            const isEvenRow = index % 2 === 0;
            const splitDescription = doc.splitTextToSize(toTitleCase(item.description), tableWidth - (descriptionColX - pageMargin));
            const rowHeight = (splitDescription.length * (itemGap - 2)) + 10;

            // Draw row background
            if (!isEvenRow) {
                doc.setFillColor(...lightGray);
                doc.rect(pageMargin, y, tableWidth, rowHeight, 'F');
            }

            const itemY = y + 15;
            const itemNumber = `${index + 1}.`;
            
            doc.text(itemNumber, numberColX + 10, itemY);
            doc.text(splitDescription, descriptionColX, itemY);
            y += rowHeight;
        });

        // Draw table borders
        doc.setDrawColor(...borderGray);
        doc.rect(pageMargin, tableTop, tableWidth, y - tableTop); // Outer border
        doc.line(descriptionColX - 10, tableTop, descriptionColX - 10, y); // Vertical line after #
        
        y += itemGap;

        // --- Totals ---
        const totalsX = doc.internal.pageSize.getWidth() - pageMargin - 200;
        doc.line(totalsX - 20, y, doc.internal.pageSize.getWidth() - pageMargin, y);
        y += itemGap + 2;
        
        const subTotal = invoice.subTotal || 0;
        const expensesTotal = invoice.expensesTotal || 0;
        const servicesTotal = subTotal - expensesTotal;
        
        let discountAmount = invoice.discountValue || 0;
        if (invoice.discountType === 'percentage') {
            discountAmount = (subTotal * discountAmount) / 100;
        }

        const discountedSubTotal = subTotal - discountAmount;
        const taxRate = invoice.taxRate || 0;
        const taxAmount = (discountedSubTotal * taxRate) / 100;
        const totalAmount = discountedSubTotal + taxAmount;

        const totals = [
            ...(expensesTotal > 0 ? [{ label: 'Services', value: `$${servicesTotal.toFixed(2)}`}] : []),
            ...(expensesTotal > 0 ? [{ label: 'Expenses', value: `$${expensesTotal.toFixed(2)}`}] : []),
            { label: 'Sub-total', value: `$${subTotal.toFixed(2)}` },
            ...(discountAmount > 0 ? [{ label: 'Discount', value: `-$${discountAmount.toFixed(2)}`, color: gray }] : []),
            { label: `Tax (${taxRate}%)`, value: `$${taxAmount.toFixed(2)}` },
            { label: 'Total', value: `$${totalAmount.toFixed(2)}`, bold: true },
        ];

        doc.setFontSize(10);
        totals.forEach(t => {
            doc.setFont('helvetica', t.bold ? 'bold' : 'normal');
            doc.setTextColor(...(t.color || (t.bold ? black : gray)));
            doc.text(t.label, totalsX, y, { align: 'left' });
            doc.text(t.value, doc.internal.pageSize.getWidth() - pageMargin, y, { align: 'right' });
            y += itemGap + (t.bold ? 4 : 2);
        });
        y += sectionGap;

        // --- Notes & Payment ---
        if (invoice.notes || invoice.paymentUrl) {
            y += sectionGap / 2;
            if (invoice.notes) {
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(...black);
                doc.text('Notes', pageMargin, y);
                y += itemGap;
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(...gray);
                const noteLines = doc.splitTextToSize(toTitleCase(invoice.notes), doc.internal.pageSize.getWidth() - (pageMargin * 2));
                doc.text(noteLines, pageMargin, y);
                y += (noteLines.length * itemGap) + sectionGap;
            }
            if (invoice.paymentUrl) {
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(...black);
                doc.text('Payment Link:', pageMargin, y);
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(59, 130, 246); // A nice blue for links
                doc.textWithLink(invoice.paymentUrl, pageMargin + 75, y, { url: invoice.paymentUrl });
                y += itemGap;
            }
        }
    };
    
    await generatePdf(`Invoice-${invoice.invoiceNumber}`, 'INVOICE', !!removeWatermark, addContent, user.is_subscribed ? user.logoUrl : undefined);
}

// --- PROPOSAL PDF ---
type GenerateProposalPdfProps = {
    proposalText: string;
    clientName?: string;
    user: UserProfile;
    removeWatermark?: boolean;
};

export async function generateProposalPdf({ proposalText, clientName, user, removeWatermark = false }: GenerateProposalPdfProps) {
    const addContent = (doc: jsPDF) => {
        let y = pageMargin + 80;

        doc.setFontSize(10);
        doc.setTextColor(...gray);
        doc.text(`DATE: ${format(new Date(), 'PPP')}`, pageMargin, y);
        if (clientName) {
            doc.text(`TO: ${clientName}`, doc.internal.pageSize.getWidth() - pageMargin, y, { align: 'right' });
        }
        y += 30;
        doc.setDrawColor(...borderGray); // border color
        doc.line(pageMargin, y, doc.internal.pageSize.getWidth() - pageMargin, y);
        y += 40;
        
        doc.setFontSize(11);
        doc.setTextColor(...black);
        doc.setLineHeightFactor(1.5);
        const textLines = doc.splitTextToSize(proposalText, doc.internal.pageSize.getWidth() - pageMargin * 2);
        
        textLines.forEach((line: string) => {
            if (y > doc.internal.pageSize.getHeight() - pageMargin - 40) {
                doc.addPage();
                addHeader(doc, 'Project Proposal', user.is_subscribed ? user.logoUrl : undefined);
                y = pageMargin + 40;
            }
            doc.text(line, pageMargin, y);
            if (line.trim() === '') {
                 y += 7; // smaller gap for paragraph breaks
            } else {
                 y += 15; // standard line height
            }
        });
    };
    const fileName = `Project-Proposal-${format(new Date(), 'yyyy-MM-dd')}`;
    await generatePdf(fileName, 'Project Proposal', !!removeWatermark, addContent, user.is_subscribed ? user.logoUrl : undefined);
}

// --- REPORT PDF ---
type ReportStats = {
  outstandingRevenue: number;
  incomeLast30d: number;
  hoursThisWeek: number;
  expensesThisMonth: number;
}
type ReportData = {
  stats: ReportStats;
  revenueData: { name: string; total: number }[];
  hoursData: { name: string; value: number }[];
  user: UserProfile;
};

export async function generateReportPdf({ stats, revenueData, hoursData, user }: ReportData) {
  const doc = new jsPDF('p', 'pt', 'a4');
  let y = pageMargin + 40;
  const fileName = `GigBillow-Report-${format(new Date(), 'yyyy-MM-dd')}`;
  
  await addHeader(doc, 'Reports Summary', user.is_subscribed ? user.logoUrl : undefined);
  
  doc.setFontSize(10);
  doc.setTextColor(...gray);
  doc.text(`Report for: ${user.displayName || 'User'}`, pageMargin, y);
  doc.text(`Generated on: ${format(new Date(), 'PPP')}`, doc.internal.pageSize.getWidth() - pageMargin, y, { align: 'right'});
  y += 30;

  // Key Metrics
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Key Metrics', pageMargin, y);
  y+=10;
   (doc as any).autoTable({
    startY: y,
    body: [
        ['Outstanding Revenue', `$${stats.outstandingRevenue.toFixed(2)}`],
        ['Income (Last 30d)', `$${stats.incomeLast30d.toFixed(2)}`],
        ['Hours This Week', `${stats.hoursThisWeek.toFixed(1)}h`],
        ['Expenses (This Month)', `$${stats.expensesThisMonth.toFixed(2)}`],
    ],
    theme: 'grid',
    styles: { fontSize: 10 },
    headStyles: { fillColor: primaryRgb },
    columnStyles: { 0: { fontStyle: 'bold' } },
  });
  y = (doc as any).lastAutoTable.finalY + 30;


  // Revenue Report
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Revenue Overview (Last 12 Months)', pageMargin, y);
  y += 20;
  (doc as any).autoTable({
    startY: y,
    head: [['Month', 'Total Revenue']],
    body: revenueData.map(d => [d.name, `$${d.total.toFixed(2)}`]),
    headStyles: { fillColor: primaryRgb },
    styles: { fontSize: 10 },
  });
  y = (doc as any).lastAutoTable.finalY + 30;

  // Hours Report
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Hours by Project (This Month)', pageMargin, y);
  y += 20;
  (doc as any).autoTable({
    startY: y,
    head: [['Project', 'Hours Logged']],
    body: hoursData.map(d => [d.name, `${d.value.toFixed(2)}h`]),
    headStyles: { fillColor: primaryRgb },
    styles: { fontSize: 10 },
  });

  addWatermark(doc);
  doc.save(`${fileName}.pdf`);
}

// --- CSV EXPORT ---
function convertToCSV(data: any[]): string {
  if (data.length === 0) return '';
  const headers = Object.keys(data[0]);
  const headerRow = headers.join(',') + '\n';
  const bodyRows = data.map(row => 
    headers.map(header => {
      let value = row[header];
      if (typeof value === 'string' && value.includes(',')) {
        return `"${value}"`;
      }
      return value;
    }).join(',')
  ).join('\n');
  return headerRow + bodyRows;
}

function downloadCSV(csvString: string, fileName: string) {
  const blob = new Blob([`\uFEFF${csvString}`], { type: 'text/csv;charset=utf-8;' }); // Add BOM for Excel
  const link = document.createElement('a');
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', fileName);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
}

type CsvReportData = {
  stats: ReportStats;
  revenueData: { name: string; total: number }[];
  hoursData: { name: string; value: number }[];
};

export function generateReportCsv({ stats, revenueData, hoursData }: CsvReportData) {
    let csvContent = '';
    
    csvContent += 'Key Metrics\n';
    const statsData = [
        { metric: 'Outstanding Revenue', value: stats.outstandingRevenue.toFixed(2) },
        { metric: 'Income (Last 30d)', value: stats.incomeLast30d.toFixed(2) },
        { metric: 'Hours This Week', value: stats.hoursThisWeek.toFixed(1) },
        { metric: 'Expenses (This Month)', value: stats.expensesThisMonth.toFixed(2) },
    ];
    csvContent += convertToCSV(statsData);
    csvContent += '\n\n'; 

    csvContent += 'Revenue Report (Last 12 Months)\n';
    csvContent += convertToCSV(revenueData.map(d => ({ month: d.name, total_revenue: d.total.toFixed(2) })));
    csvContent += '\n\n'; 
    
    csvContent += 'Hours by Project (This Month)\n';
    csvContent += convertToCSV(hoursData.map(d => ({ project: d.name, hours_logged: d.value.toFixed(2) })));

    const fileName = `GigBillow-Report-${format(new Date(), 'yyyy-MM-dd')}.csv`;
    downloadCSV(csvContent, fileName);
}
