
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Link from "next/link";

export default function TermsOfServicePage() {
  return (
    <div className="bg-secondary/30">
        <div className="container mx-auto py-12 md:py-24 lg:py-32 px-4 md:px-6">
        <Card className="max-w-4xl mx-auto">
            <CardHeader>
            <CardTitle className="text-3xl font-bold tracking-tight">Terms of Service</CardTitle>
            <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
            </CardHeader>
            <CardContent className="space-y-6">
            
            <p className="leading-relaxed text-muted-foreground">Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the GigBillow application (the "Service") operated by us.</p>
            
            <p className="leading-relaxed text-muted-foreground">Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.</p>

            <div>
                <h2 className="text-xl font-semibold mb-2">1. Accounts</h2>
                <p className="leading-relaxed text-muted-foreground">When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p>
                <p className="leading-relaxed text-muted-foreground mt-2">You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.</p>
            </div>
            
            <div>
                <h2 className="text-xl font-semibold mb-2">2. Use of the Service</h2>
                <p className="leading-relaxed text-muted-foreground">GigBillow provides a suite of tools for freelancers. You agree not to misuse the Service. For example, you must not, and must not attempt to, do the following things:</p>
                <ul className="list-disc list-inside space-y-2 mt-2 pl-4 text-muted-foreground">
                    <li>Use the Service for any unlawful purposes or for promotion of illegal activities.</li>
                    <li>Post any content on the Service in violation of any applicable law, including intellectual property laws and right of privacy or publicity laws, or any contractual obligation.</li>
                    <li>Impersonate others through the Service or otherwise misrepresent your affiliation with a person or entity in a manner that does or is intended to mislead, confuse, or deceive others.</li>
                </ul>
            </div>

            <div>
                <h2 className="text-xl font-semibold mb-2">3. AI-Generated Content</h2>
                <p className="leading-relaxed text-muted-foreground">The Service uses artificial intelligence (AI) to generate content, such as proposals and invoice summaries. While we strive to provide high-quality output, we make no guarantees as to the accuracy, completeness, or suitability of the AI-generated content. You are solely responsible for reviewing, editing, and verifying any content generated by the AI before using it for any purpose. We are not liable for any errors, inaccuracies, or any damages arising from your use of the AI-generated content.</p>
            </div>

            <div>
                <h2 className="text-xl font-semibold mb-2">4. Payments and Tokens</h2>
                <p className="leading-relaxed text-muted-foreground">Certain features of the Service are available upon the use of "Tokens". Tokens can be acquired through free monthly allocations or by purchasing one-time packs. All purchases are processed through a third-party payment processor (Stripe). By making a purchase, you agree to the terms of our payment processor.</p>
                <p className="leading-relaxed text-muted-foreground mt-2">Token costs for features are subject to change. We will provide notice of any changes to token costs. Purchased tokens have an expiration date as specified at the time of purchase.</p>
            </div>

            <div>
                <h2 className="text-xl font-semibold mb-2">5. Termination</h2>
                <p className="leading-relaxed text-muted-foreground">We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
                <p className="leading-relaxed text-muted-foreground mt-2">Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may do so by contacting us.</p>
            </div>

            <div>
                <h2 className="text-xl font-semibold mb-2">6. Limitation Of Liability</h2>
                <p className="leading-relaxed text-muted-foreground">In no event shall GigBillow, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
            </div>

            <div>
                <h2 className="text-xl font-semibold mb-2">7. Changes</h2>
                <p className="leading-relaxed text-muted-foreground">We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
            </div>
            
            <div>
                <h2 className="text-xl font-semibold mb-2">8. Contact Us</h2>
                <p className="leading-relaxed text-muted-foreground">If you have any questions about these Terms, please contact us at: <a href="mailto:support@gigbillow.com" className="text-primary hover:underline">support@gigbillow.com</a>.</p>
            </div>
            
            <div className="text-center mt-8">
                <Link href="/" className="text-primary hover:underline">
                    &larr; Back to Home
                </Link>
            </div>
            </CardContent>
        </Card>
        </div>
    </div>
  );
}
